name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      changed_dirs: ${{ steps.detect-changes.outputs.changed_dirs }}
    steps:
      - uses: actions/checkout@v4
      - name: Grant execute permission for detect-changes.sh
        run: chmod +x ./.github/scripts/detect-changes.sh
      - name: Detect changed directories
        id: detect-changes
        run: ./.github/scripts/detect-changes.sh

  build:
    needs: detect-changes
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Build and test api_gateway
        if: contains(env.changed_dirs, 'api_gateway')
        working-directory: api_gateway
        run: |
          npm ci
          npm run build --if-present
          npm test

      - name: Build and test service_registry
        if: contains(env.changed_dirs, 'service_registry')
        working-directory: service_registry
        run: |
          npm ci
          npm run build --if-present
          npm test
