name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4

      - name: Build and test api_gateway
        working-directory: ./api_gateway
        run: |
          npm i
          npm run

      - name: Build and test service_registry
        working-directory: ./service_registry
        run: |
          npm i
          npm run

      - name: Build and test service_auth
        working-directory: ./service_authentication
        run: |
          npm i
          npm run

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image for api_gateway
        working-directory: ./api_gateway
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/api_gateway:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/api_gateway:latest

      - name: Build and push Docker image for service_registry
        working-directory: ./service_registry
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/service_registry:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/service_registry:latest

      - name: Build and push Docker image for service_auth
        working-directory: ./service_authentication
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/service_auth:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/service_auth:latest
